Задачи из разделов основы и компоненты
js-tasks-ru/vue-20240924_sergey48 pull request #4
Opened 2024-10-06 21:00 UTC by slenshin

2024-10-06 21:00 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-06 21:44 UTC, ShGKme requested changes
В `03-components/30-removable-emails` требуется добавить опцию `emits`. Остальные задачи приняты.

2024-10-06 21:44 UTC, ShGKme commented on 03-components/30-removable-emails/EmailList.js
> +        @delete-email="$emit('delete-email', index)"
В JS части (включая значения директив) принято всегда работать в `camelCase`: `$emit('deleteEmail', index)`

2024-10-06 21:44 UTC, ShGKme commented on 03-components/10-MeetupView/MeetupView.js
> +            </template>
Оборачивание в `template` требуется только, если нужен `v-if`/`v-for` на 2 и более узлов. На один узел можно установить директиву напрямую.

2024-10-06 21:44 UTC, ShGKme commented on 03-components/30-removable-emails/EmailList.js
> +        @delete-email="$emit('delete-email', index)"
Хотя компонент работает и без явного описания событий в `emits`, настоятельно рекомендуется всегда описывать события в `emits`:
- Так у компонента есть документация и типизация для разработчиков и различных инструментов
- В случае, если имя события совпадает с DOM событием, оно будет дублироваться

2024-10-07 06:55 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-07 17:52 UTC, ShGKme approved these changes, later dismissed

2024-10-08 09:53 UTC, slenshin commented
Пулл реквест долго висел не закрытым, думал это стоит сделать мне, но ошибся.
Вижу что мердж вызывает закрытие реквеста.

2024-10-08 09:54 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-08 09:54 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-08 16:25 UTC, ShGKme approved these changes

2024-10-08 16:25 UTC, merged